# Generated by Django 4.2 on 2025-06-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_certificate"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="certificate_file",
            field=models.FileField(blank=True, null=True, upload_to="certificates/"),
        ),
    ]
