# Generated by Django 4.2 on 2025-06-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_enrollment"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="cloudinary_public_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="video_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
