# Generated by Django 4.2 on 2025-06-10 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_lessonviewanalytics_lessonprogress_lessonbookmark"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessonprogress",
            name="last_accessed",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="lessonprogress",
            name="last_watched",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
