# Generated by Django 4.2 on 2025-06-10 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0008_notification_usernotification"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="usernotification",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="usernotification",
            name="notification",
        ),
        migrations.RemoveField(
            model_name="usernotification",
            name="user",
        ),
        migrations.DeleteModel(
            name="Notification",
        ),
        migrations.DeleteModel(
            name="UserNotification",
        ),
    ]
